//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class menu13Entities : DbContext
    {
        public menu13Entities()
            : base("name=menu13Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alimentos> alimentos { get; set; }
        public virtual DbSet<bebidas> bebidas { get; set; }
        public virtual DbSet<metodos_pago> metodos_pago { get; set; }
        public virtual DbSet<opciones_para_llevar> opciones_para_llevar { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
    }
}
